name: Configure Lab Private Cloud
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: [self-hosted, terraform]

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"

      # vSphere / vRA / VCF environment-specific credentials
      TF_VAR_serviceAccountUserName: ${{ secrets.VCF_SERVICE_USER }}
      TF_VAR_serviceAccountPassword: ${{ secrets.VCF_SERVICE_PASSWORD }}
      TF_VAR_vcfa_refresh_token: ${{ secrets.VCFA_API_TOKEN}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: |
             terraform init -migrate-state -input=false -upgrade \

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
              terraform plan -input=false -no-color \
              -var-file="envs/lab.tfvars" \
              -out=tfplan

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -input=false -auto-approve tfplan

      - name: Clean workspace
        run: rm -rf $GITHUB_WORKSPACE/.[!.]*
